# Generated by Django 4.2.6 on 2023-10-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_user_email_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telehpone",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
