# Generated by Django 4.2.6 on 2023-10-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_prompt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prompt",
            old_name="text",
            new_name="text1",
        ),
        migrations.RenameField(
            model_name="prompt",
            old_name="title",
            new_name="title1",
        ),
        migrations.RenameField(
            model_name="prompt",
            old_name="username",
            new_name="username1",
        ),
    ]
