# Generated by Django 4.2.6 on 2023-10-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_rename_text_prompt_text1_rename_title_prompt_title1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prompt",
            old_name="text1",
            new_name="text",
        ),
        migrations.RenameField(
            model_name="prompt",
            old_name="title1",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="prompt",
            old_name="username1",
            new_name="username",
        ),
    ]
