# Generated by Django 4.2.6 on 2023-10-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_rename_text1_prompt_text_rename_title1_prompt_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prompt",
            old_name="title",
            new_name="navn",
        ),
        migrations.RenameField(
            model_name="prompt",
            old_name="text",
            new_name="tekst",
        ),
        migrations.RenameField(
            model_name="prompt",
            old_name="username",
            new_name="tittel",
        ),
    ]
